store/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BucketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register('products', ProductModelViewSet)
router.register('products', BucketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

store/orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='index'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('success/', SuccessTemplateView.as_view(), name='success'),
    path('cancel/', CancelTemplateView.as_view(), name='cancel'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),

    # github OAuth
    path('accounts/', include('allauth.urls')),

    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token)
]


if settings.DEBUG:
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

store/orders/models.py
from django.db import models

from products.models import Bucket
from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name: str = models.CharField(max_length=64)
    last_name: str = models.CharField(max_length=64)
    email: str = models.EmailField(max_length=256)
    address: str = models.CharField(max_length=256)
    bucket_history = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)

    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{type(self).__name__}(id={self.id}, status={self.status}, user={self.user})'

    def update_after_payment(self):
        buckets = Bucket.objects.filter(user=self.user)
        self.status = self.PAID
        self.bucket_history = {
            'purchased_items': [b.to_json() for b in buckets],
            'total_sum': float(buckets.total_sum()),
        }

        buckets.delete()
        self.save()

store/orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Имя'
            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Фамилию'
            }
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Почта'
            }
        )
    )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Адрес'
            }
        )
    )

    class Meta:
        model = Order
        fields = 'first_name', 'last_name', 'email', 'address'

    # def save(self, commit=True):
    #     user = super().save(commit=commit)
    #     send_email_verif.delay(user.id)
    #     return user

store/orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order
from products.models import Bucket

stripe.api_key = settings.STRIPE_SECRET


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context = {
            'title': f'Order #{self.object.id}'
        }

        context_data.update(context)
        return context_data


class OrderListView(TitleMixin, ListView):
    queryset = Order.objects.all()
    # model = Order
    title = 'My Orders'
    template_name = 'orders/orders.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'Success'


class CancelTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/cancel.html'
    title = 'Order canceled'


class OrderCreateView(TitleMixin, CreateView):
    title = 'Order processing'
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:create')

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        buckets = Bucket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=buckets.get_line_items(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url=f'{settings.DOMAIN_NAME}{reverse("orders:success")}',
            cancel_url=f'{settings.DOMAIN_NAME}{reverse("orders:cancel")}',
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        return HttpResponse(status=400)
    if event['type'] == 'checkout.session.completed':
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
        )
        # line_items = session.line_items
        fulfill_order(session)
    return HttpResponse(status=200)


def fulfill_order(session):
    # TODO: fill me in
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()
    print("Fulfilling order")

store/orders/templates/orders/cancel.html
<!DOCTYPE html>
<html>
<head>
    <title>Checkout canceled</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>
</body>
</html>

store/orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
    <section>
        <div class="alert alert-warning text-center" role="alert">
            Пожалуйста, заполните адрес электронной почты.
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                {% if bucket %}
                    <div class="col-md-5 col-lg-4 order-md-last">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-primary">Корзина</span>
                            <span class="badge badge-primary badge-pill text-white">{{ bucket.total_qty }}</span>
                        </h4>
                        <ul class="list-group mb-3">
                            {% for item in bucket %}
                                <li class="list-group-item d-flex justify-content-between lh-sm">
                                    <div>
                                        <h6 class="my-0">{{ item.product.title }}</h6>
                                        <small class="text-muted">{{ item.qty }} шт.</small>
                                    </div>
                                    <span class="text-muted">{{ item.sum|intcomma }} usd.</span>
                                </li>
                            {% endfor %}
                            <li class="list-group-item d-flex justify-content-between">
                                <span>Сумма к оплате</span>
                                <strong>{{ bucket.total_sum|intcomma }} usd.</strong>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <div class="col-lg-4 order-md-last">
                        <h4 class="text-center">
                            <span style="color: black">Корзина пуста</span>
                        </h4>
                    </div>
                {% endif %}
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Адрес доставки</h4>
                    <form action="{% url 'orders:create' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>
                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                            <div class="col-12 mt-3">
                                <label for="{{ form.address.id_for_label }}" class="form-label">Адрес</label>
                                {{ form.address }}
                            </div>
                        </div>
                        <hr class="my-4">
                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

store/orders/templates/orders/order.html
{% extends 'products/base.html' %}

{% load humanize %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>{{ title }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Кол-во</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Сумма</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for purchased_item in object.bucket_history.purchased_items %}
                            <tr>
                                <th scope="row">
                                    {{ purchased_item.product_name }}
                                </th>
                                <td>{{ purchased_item.quantity }}</td>
                                <td>{{ purchased_item.price|intcomma }} usd</td>
                                <td>{{ purchased_item.sum|intcomma }} usd</td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Итого {{ object.bucket_history.total_sum|intcomma }} usd.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

store/orders/templates/orders/orders.html
{% extends 'products/base.html' %}

{% load humanize %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказы</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Итого</th>
                            <th scope="col">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.created_at|naturaltime }}</td>
                                <td>{{ order.bucket_history.total_sum|intcomma }} usd</td>
                                <td>
                                    <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

store/orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block content %}
    <meta http-equiv="refresh" content="2; url = {% url 'orders:index' %}"/>
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Ваш заказ успешно сформирован.
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}